export const products = [
  {
    id: "0001",
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 100,
    colors: ["white"],
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0002",
    title: "Secundaria - White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 200,
    colors: ["white"],
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0003",
    title: "Primaria - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 300,
    colors: ["white"],
    sizes: ["12", "14", "S", "M"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0004",
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    colors: ["white"],
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
];

export const promotions = [
  {
    id: "0005",
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0006",
    title: "Secundaria - White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0007",
    title: "Primaria - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["12", "14", "S", "M"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0008",
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0009",
    title: "Secundaria - White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
  {
    id: "0010",
    title: "Primaria - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["12", "14", "S", "M"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
  },
];
