export const products = [
  {
    id: "0001",
    title: "Short deportivo",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 59.99,
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/short_buzo.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0002",
    title: "Polo manga corta",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 200,
    sizes: ["S", "M", "L"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0003",
    title: "Buzo deportivo",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 300,
    sizes: ["12", "14", "S", "M"],
    categories: ["inicial"],
    image: "/buzo.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0004",
    title: "Media deportivas blancas",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0005",
    title: "Zapatillas negras",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0006",
    title: "Polo manga larga",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0007",
    title: "Casaca de invierno",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0010",
    title: "Short deportivo",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 100,
    sizes: ["10", "12", "14"],
    categories: ["primaria"],
    image: "/short_buzo.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0011",
    title: "Polo manga corta",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 200,
    sizes: ["S", "M", "L"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0012",
    title: "Buzo deportivo",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 300,
    sizes: ["12", "14", "S", "M"],
    categories: ["primaria"],
    image: "/buzo.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0013",
    title: "Media deportivas blancas",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0014",
    title: "Zapatillas negras",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0015",
    title: "Polo manga larga",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0016",
    title: "Casaca de invierno",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0017",
    title: "Mandil de vichy",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0020",
    title: "Blusa",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 100,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0021",
    title: "Camisa",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 200,
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/camisa.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0022",
    title: "Falda",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 300,
    sizes: ["12", "14", "S", "M"],
    categories: ["secundaria"],
    image: "/falda.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0023",
    title: "Media altas",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0024",
    title: "Zapatos negros",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0025",
    title: "Chompa",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0026",
    title: "Buzo deportivo",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/buzo.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0027",
    title: "Casaca de invierno",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0028",
    title: "Short deportivo",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 100,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/short_buzo.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0029",
    title: "Polo manga corta",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 200,
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0030",
    title: "Mandil de laboratorio",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 200,
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0031",
    title: "Medias deportivas blancas",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0032",
    title: "Zapatillas negras",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0033",
    title: "Polo manga larga",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 400,
    sizes: ["10", "12", "14"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
];

export const promotions = [
  {
    id: "0005",
    title: "Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    sizes: ["10", "12", "14"],
    categories: ["inicial"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0006",
    title: "Secundaria - White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    sizes: ["S", "M", "L"],
    categories: ["secundaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
  {
    id: "0007",
    title: "Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    sizes: ["12", "14", "S", "M"],
    categories: ["primaria"],
    image: "/phone.png",
    createdAt: "10/12/2023",
    cantidad: 0,
  },
];
