export const products = [
  {
    id: 1,
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["s"],
    categories: ["inicial"],
    image: "/boat.png",
    createdAt: "10/12/2023",
  },
  {
    id: 2,
    title: "Secundaria - White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["m"],
    categories: ["secundaria"],
    image: "/img-1.png",
    createdAt: "10/12/2023",
  },
  {
    id: 3,
    title: "Primaria - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["s"],
    categories: ["primaria"],
    image: "/img-2.png",
    createdAt: "10/12/2023",
  },
  {
    id: 4,
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["s"],
    categories: ["inicial"],
    image: "/boat.png",
    createdAt: "10/12/2023",
  },
];

export const promotions = [
  {
    id: 1,
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["s"],
    categories: ["inicial"],
    image: "/boat.png",
    createdAt: "10/12/2023",
  },
  {
    id: 2,
    title: "Secundaria - White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["m"],
    categories: ["secundaria"],
    image: "/img-1.png",
    createdAt: "10/12/2023",
  },
  {
    id: 3,
    title: "Primaria - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["s"],
    categories: ["primaria"],
    image: "/img-2.png",
    createdAt: "10/12/2023",
  },
  {
    id: 1,
    title: "Inicial - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["s"],
    categories: ["inicial"],
    image: "/boat.png",
    createdAt: "10/12/2023",
  },
  {
    id: 2,
    title: "Secundaria - White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["m"],
    categories: ["secundaria"],
    image: "/img-1.png",
    createdAt: "10/12/2023",
  },
  {
    id: 3,
    title: "Primaria - Women White T-Shirt",
    desc: "Lorem Ipsun lorem ipsum padf aspdasdf asdfsfsad asdfasdfasd lorem impsun",
    price: 550,
    colors: ["white"],
    sizes: ["s"],
    categories: ["primaria"],
    image: "/img-2.png",
    createdAt: "10/12/2023",
  },
];

