name: Notify on Push

on:
  push:
    branches:
      - main
      - uat

jobs:
  build-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check out the repository for push
        if: github.event_name == 'push'
        uses: actions/checkout@v3

      - name: Check out the repository for pull request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} #obtiene el SHA del commit en la cabeza del PR

      - name: Get commit details
        id: get_commit_details
        run: |
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Get detail user pushing
        run: |
          echo "Usuario: ${{ env.COMMIT_AUTHOR }} subio cambios, commit: ${{ env.COMMIT_MESSAGE }}"

      - name: Send notification email
        run: |
          echo "Sending email notification..."
          sudo apt-get install -y ssmtp
          echo "root=postmaster" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "mailhub=${{ secrets.SMTP_SERVER }}:${{ secrets.SMTP_PORT }}" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "AuthUser=${{ secrets.SMTP_USERNAME }}" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "AuthPass=${{ secrets.SMTP_PASSWORD }}" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "UseTLS=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "UseSTARTTLS=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "FromLineOverride=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf

          echo -e "To: ${{ secrets.EMAIL_TO }}\nSubject: New Push to ${{ github.ref_name }}\n\nCommit by: ${{ env.COMMIT_AUTHOR }}\nMessage: ${{ env.COMMIT_MESSAGE }}" | ssmtp ${{ secrets.EMAIL_TO }}
          